### PR TITLE
cuberevo_250hd sound fixed  

### PR DESCRIPTION
**Pull request by backup1977**

### CODE REVIEW

**Comment by persianpros** [comment]
Patches are just empty files?

**Comment by backup1977** [comment]
yes, because other models do not need it. there are problems with the sun build comes with other models, because of this I have inserted this blank patch for everyone to build normally

the most important patch for cuberevo 250 is here
https://github.com/OpenVisionE2/meta-fulan/blob/d69cad9d6ec62e04f51413784138fb24477148db/recipes-bsp/linux/linux-fulan/cuberevo_250hd/linux-sh4-cuberevo_250hd_sound_stm24_0217.patch

**Comment by backup1977** [comment]
so without this empty patch it does not build on other models, and since they do not need this patch like cuberevo 250hd I've inserted a blank patch, and now builds it normal
only cuberevo 250 needs such a sound patch

**Comment by persianpros** [comment]
I did it but in a better way ;)
https://github.com/OpenVisionE2/meta-fulan/blob/develop/recipes-bsp/linux/linux-fulan-cuberevo_2.6.32.bb
Thanks a lot 👍

**Pull request closed without merging**
