### PR TITLE
[cuberevo] fixed shutdown

### PR DESCRIPTION
**Pull request by backup1977**

### CODE REVIEW

**Comment by persianpros** [comment]
Is it going to affect other boxes too?

**Comment by backup1977** [comment]
I think so, because each box has different settings, see here
https://github.com/Audioniek/buildsystem/blob/master/root/release/halt_cuberevo
https://github.com/Audioniek/buildsystem/blob/master/root/release/halt_spark
https://github.com/Audioniek/buildsystem/blob/master/root/release/halt_fortis_hdbox

**Comment by persianpros** [comment]
Then what's going to happend for the rest if we merge this?

**Comment by persianpros** [comment]
Done: https://github.com/OpenVisionE2/meta-fulan/commit/0a13b7f54f6e2712d01321bb3d34d10ccdb25fc5 thanks to you 👍

**Pull request closed without merging**
